#Requires -Version 7.0
<#
.SYNOPSIS
    Regenerates module/IntuneTenantCloneKit/Public/*.ps1 from the en/ bundle scripts.

.DESCRIPTION
    The distributable module reuses the exact, battle-tested logic of the en/ scripts.
    Each param-based script is wrapped verbatim into an advanced function with an
    approved-verb name (single source of truth = the en/ scripts). Re-run this after
    editing any en/ script, then bump the ModuleVersion in the .psd1 before publishing.

    Transformations applied while wrapping:
      - drop the top-level '#Requires' line (PowerShellVersion lives in the manifest);
      - turn any top-level 'exit N' into 'return N' (a module function must not kill the host,
        but its return code must stay usable in CI).

.EXAMPLE
    pwsh ./module/Build-Module.ps1
#>
[CmdletBinding()]
param(
    [string]$RepoRoot = (Split-Path -Parent $PSScriptRoot)
)

$ErrorActionPreference = 'Stop'

# Source script (relative to en/) -> exported cmdlet name (approved verb).
$map = [ordered]@{
    'scripts/Export-IntuneConfig_FraisComplet_v1.ps1'    = 'Export-IntuneConfiguration'
    'scripts/Import-IntuneConfig_Corrige_v3.ps1'         = 'Import-IntuneConfiguration'
    'scripts/Compare-IntuneExport.ps1'                   = 'Compare-IntuneExport'
    'scripts/Verify-IntuneExport.ps1'                    = 'Test-IntuneExport'
    'scripts/Invoke-IntuneAssignments_Graph.ps1'         = 'Copy-IntuneAssignment'
    'scripts/Build-IntuneAppIdMap.ps1'                   = 'New-IntuneAppIdMap'
    'scripts/Invoke-IntuneImportCleanupFromReport.ps1'   = 'Remove-IntuneImportedObject'
    'scripts/Recover-IntuneScriptContentsFromProd.ps1'   = 'Restore-IntuneScriptContent'
    'scripts/Recover-IntuneOmaSecrets.ps1'               = 'Restore-IntuneOmaSecret'
    'scripts/Invoke-IntuneAIAssist.ps1'                  = 'Invoke-IntuneAIAssist'
    'scripts/Invoke-IntunePortalCaptureToScript.ps1'     = 'Convert-IntunePortalCapture'
    'scripts/Publish-IntuneApp.ps1'                      = 'Publish-IntuneApp'
    'tools/New-IntuneCloneKitAppRegistration.ps1'        = 'New-IntuneCloneAppRegistration'
}

$src = Join-Path $RepoRoot 'en'
$pub = Join-Path $PSScriptRoot 'IntuneTenantCloneKit/Public'
New-Item -ItemType Directory -Force -Path $pub | Out-Null
Get-ChildItem $pub -Filter *.ps1 -ErrorAction SilentlyContinue | Remove-Item -Force

$names = @()
foreach ($rel in $map.Keys) {
    $fn   = $map[$rel]
    $path = Join-Path $src $rel
    if (-not (Test-Path -LiteralPath $path)) { throw "Source script not found: $path" }

    $out = foreach ($ln in (Get-Content -LiteralPath $path)) {
        if ($ln -match '^\s*#Requires')      { continue }
        if ($ln -match '^(?<i>\s*)exit\b(?<rest>.*)$') { "$($Matches.i)return$($Matches.rest)"; continue }
        $ln
    }

    $header  = "# Auto-generated by module/Build-Module.ps1 from en/$rel"
    $header += "`n# Edit the source script, then re-run Build-Module.ps1. Do not edit this file directly.`n"
    $content = "$header`nfunction $fn {`n" + ($out -join "`n") + "`n}`n"
    [System.IO.File]::WriteAllText((Join-Path $pub "$fn.ps1"), ($content -replace "`r`n","`n"))
    Write-Host ("  en/{0,-48} -> {1}" -f $rel, $fn) -ForegroundColor Green
    $names += $fn
}

Write-Host ("`nGenerated {0} function file(s) in {1}" -f $names.Count, $pub) -ForegroundColor Cyan
Write-Host ("FunctionsToExport = @({0})" -f (($names | ForEach-Object { "'$_'" }) -join ', ')) -ForegroundColor DarkGray
